### ISSUE TITLE
minimum duration argument name consitency

### ISSUE THREAD

**Issue by ablack3** [darwin-eu-dev/TreatmentPatterns#107]
It might be too late to make changes but I think doCombinationWindow argument names are worth some discussion.

1. `treatment_history` - Uses snake case. Are we officially OK with mixing snake and camel case?
2. `combinationWindow` - The minimum number of days an overlap must occur to be counted as a combination. There are several "minimum duration" arguments in the package and their naming could be more consistent.
3. `minPostDuration` - This is the minimum number of days an event must persist ***before or after*** a combination to be include. The name implies this should only apply to time after (post) combination.

Minimum duration arguments with rename suggestions.

`minPostDuration` -> `minPrePostDuration`
`combinationWindow` -> `minOverlapDuration`
`minEraDuration`

Can `minPostDuration` be less than `minEraDuration`? If so then it means we can end up with event eras in the output whose length is less than `minEraDuration` which seems incorrect to me.

Would it be possible to simply use `minEraDuration` as the `minPostDuration` value or are there use cases when these need to be controlled separately?

Should we guarantee that all eras in the output are greater than or equal to `minEraDuration` in length?

@AniekMarkus @edward-burn @mvankessel-EMC

**Comment by AniekMarkus** [comment]
1. As "treatment_history" is only used inside the package, I would definitely change that according to style guidelines.

2/3. Regarding the names of the parameters, the original names were: _minEraDuration_ referring to applying min duration to treatment eras and _minPostCombinationDuration_ referring to applying min duration post generating combinations (not sure where 'combination' went?). For me "PrePost" would be more confusing as to when it is applied.

Furthermore, _combinationWindow_ was chosen because this was also how it was called in the cohort pathways tool in ATLAS. This could be changed, but the package actually uses min(total duration era, combinationWindow) to look for overlapping treatments (as discussed in example 1 in other issue), not sure if _minOverlapDuration_ might therefore be more misleading.

- _minEraDuration_ is first applied to ALL extracted treatment eras (for a researcher to influence the duration of time someone should be exposed to a treatment for it to included in the treatment pathway)
-  _minPostDuration/minPostCombinationDuration_ is only applied to treatment eras that remain pre/post generated combination treatments (for a researcher to influence whether or not these remaining eras are important enough to be included in the treatment pathway), this is done so that _minPostDuration/minPostCombinationDuration_ can be both larger and smaller than _minEraDuration_.

For simplification, you could set _minPostDuration/minPostCombinationDuration_ to _minEraDuration_ as default (and even leave out of study templates), but I would keep both for flexibility. 

You should not guarantee that all output eras are greater than or equal to _minEraDuration_, because then also _combinationTreatment_ behavior is overruled.

**Comment by mvankessel-EMC** [comment]
1. `treatment_history` has been renamed to `treatmentHistory`
2. `combinationWindow` was left as is.
3. `minEraDuration` was left as is.
