### ISSUE TITLE
What is the purpose of the `writeCohortTable()` function?

### ISSUE THREAD

**Issue by schuemie** [darwin-eu-dev/TreatmentPatterns#142]
I'm following the vignette, which describes first calling `writeCohortTable()`, and then `constructPathways()`.

`writeCohortTable()` downloads all the cohorts, and writes them to disc in CSV table.

However, the `constructPathways()` function does not use this CSV file. Instead, the first thing it does is download all the cohorts (again), and stores them internally as a Data Table: https://github.com/darwin-eu-dev/TreatmentPatterns/blob/drat/R/ConstructPathways.R#L81. Is this intentional? If so, why would I call the `writeCohortTable()` function?

**Comment by mvankessel-EMC** [comment]
In the original version of TreatmentPatterns, cohorts were generated 'in house'. The cohort table was also generated in this section of code. We've since moved away from that, and leave it up to the user how to generate their cohorts. `writeCohortTable()` was a way to ensure the cohort table actually existed. I've changed this in PR #144 so it is now being written when constructing the pathways.
