### ISSUE TITLE
Questions on input.

### ISSUE THREAD

**Issue by ilovemane** [darwin-eu-dev/TreatmentPatterns#151]
Hi, I have few question on the input of pathway settings, as I am working on a darwin study that need to use this package

1) I am not sure what minCellMethod does?

2) Also I am not sure what groupcombinations does? What is non-fixed combinations?

3) Also want to confirm do treatmentpattern collapse the event according to the eraCollapseSize before working out the treatment pathway? 

thanks in advance!

**Comment by mvankessel-EMC** [comment]
Hi Mike,

1. `minCellMethod` specifies a way how to handle treatment pathways that fall below the specified `minCellCount`. By default this is set to `"Remove"`, which removes these pathways below the specified cut-off.
2. There is an error in the documentation, `groupCombinations` should be of data type `boolean`. When building the treatment pathways certain drug era's will over lap. I.e. **Drug A** will be taken at the same time as **Drug B**. This will be picked up as one treatment. If `groupCombinations` is set to `TRUE` all occurring combinations will be grouped under the label "Other". Otherwise they will have the label "Drug A+Drug B", "Drug B+Drug C", "Drug A+Drug C", etc.
3. Yes, that is correct.

**Comment by ilovemane** [comment]
thanks a lot
